cdef void PK2toCauchy(double [:],
                      double [:],
                      double [:],
                      int [:, ::1],
                      unsigned int,
                      double,
                      double,
                      double,
                      double [:, :],
                      double [:])